name: Automated API tests using Postman CLI and Newman

on:
  push:
  schedule:
    - cron: '0 10 * * *'  # 10:00 AM UTC
    - cron: '0 17 * * *'  # 5:00 PM UTC

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Newman tests and generate reports
        run: |
          mkdir -p ./newman
          newman run https://api.postman.com/collections/39430124-8ad8fea8-76ea-4a78-8faf-49f1797cd967?apikey=${{ secrets.POSTMAN_API_KEY }} \
            --environment https://api.postman.com/environments/39430124-bd3179f0-392f-42b4-a4cc-3431dd17744e?apikey=${{ secrets.POSTMAN_API_KEY }} \
            --reporters cli,html,json \
            --reporter-html-export ./newman/report.html \
            --reporter-json-export ./newman/report.json

      - name: Upload Newman Reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-api-test-report
          path: ./newman/
