name: Automated API tests using Postman CLI 

on:
  push:
  schedule:
    - cron: '0 8 * * *'  # 01:30 PM IST

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests 3 times and generate reports
        run: |
          mkdir -p ./postman
          for i in 1 2 3; do
            echo "Running iteration $i"
            postman collection run "39430124-8ad8fea8-76ea-4a78-8faf-49f1797cd967" \
              -e "39430124-bd3179f0-392f-42b4-a4cc-3431dd17744e" \
              --reporters cli,json,html \
              --reporter-html-export ./postman/report-$i.html \
              --reporter-json-export ./postman/report-$i.json
          done

      - name: Upload Test Reports (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: postman-api-test-reports
          path: ./postman/

      - name: Send Test Reports via Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Automated Postman API Test Reports (3 Iterations)"
          to: ${{ secrets.TO_EMAIL }}
          from: "GitHub Actions <${{ secrets.GMAIL_USER }}>"

          html_body: |
            <p>Hello,</p>
            <p>Attached are the Postman API test reports generated from 3 test iterations run by GitHub Actions.</p>
            <ul>
              <li>report-1.html</li>
              <li>report-2.html</li>
              <li>report-3.html</li>
            </ul>
            <p>Regards,<br/>CI Bot</p>
          attachments: |
            ./postman/report-1.html
            ./postman/report-2.html
            ./postman/report-3.html
