name: Automated API tests using Postman CLI

on:
  push:
  schedule:
    - cron: '30 3 * * *'  # 09:00 AM IST
    - cron: '30 10 * * *' # 04:00 PM IST

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests and generate report
        id: run_tests
        run: |
          mkdir -p ./postman
          set +e
          postman collection run "39430124-8ad8fea8-76ea-4a78-8faf-49f1797cd967" \
            -e "39430124-bd3179f0-392f-42b4-a4cc-3431dd17744e" \
            --reporters cli,json,html \
            --reporter-html-export ./postman/report.html \
            --reporter-json-export ./postman/report.json
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload Test Report (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-api-test-report
          path: ./postman/

      - name: Send Email - Test Passed
        if: steps.run_tests.outputs.exit_code == '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "✅ Postman API Test Report - All Tests Passed"
          to: ${{ secrets.TO_EMAIL }}
          from: "GitHub Actions <${{ secrets.GMAIL_USER }}>"
          html_body: |
            <p>Hello,</p>
            <p>All Postman API tests passed successfully. See the attached report for details.</p>
            <p>Regards,<br/>CI Bot</p>
          attachments: ./postman/report.html

      - name: Send Email - Test Failed
        if: steps.run_tests.outputs.exit_code != '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "❌ Postman API Test Report - Test Failures Detected"
          to: ${{ secrets.TO_EMAIL }}
          from: "GitHub Actions <${{ secrets.GMAIL_USER }}>"
          html_body: |
            <p>Hello,</p>
            <p><strong>One or more API tests have failed.</strong> Please review the attached report.</p>
            <p>Regards,<br/>CI Bot</p>
          attachments: ./postman/report.html
