name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests and generate report
        run: |
          postman collection run "39430124-xxxx" \
            -e "39430124-yyyy" \
            --reporters cli,json,html \
            --reporter-html-export ./postman/report.html \
            --reporter-json-export ./postman/report.json

      - name: Upload Test Report (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: postman-api-test-report
          path: ./postman/

      - name: Install mailsend-go
        run: |
          curl -L https://github.com/muquit/mailsend-go/releases/latest/download/mailsend-go-linux-amd64 -o mailsend-go
          chmod +x mailsend-go
          sudo mv mailsend-go /usr/local/bin/

      - name: Send Email via Gmail SMTP
        run: |
          mailsend-go \
            -smtp smtp.gmail.com \
            -port 587 \
            -auth \
            -user "${{ secrets.SMTP_USER }}" \
            -pass "${{ secrets.SMTP_PASS }}" \
            -from "${{ secrets.SMTP_USER }}" \
            -to "${{ secrets.TO_EMAIL }}" \
            -sub "Postman API Test Report" \
            -attach ./postman/report.html \
            -M "Hello,\n\nPlease find the attached Postman test report.\n\nRegards,\nGitHub Actions"
