name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests and generate report
        run: |
          postman collection run "39430124-8ad8fea8-76ea-4a78-8faf-49f1797cd967" \
            -e "39430124-bd3179f0-392f-42b4-a4cc-3431dd17744e" \
            --reporters cli,json,html \
            --reporter-html-export ./postman/report.html \
            --reporter-json-export ./postman/report.json

      - name: Upload Test Report (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: postman-api-test-report
          path: ./postman/

      - name: Install msmtp and mutt
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp mutt

      - name: Configure msmtp
        run: |
          echo "defaults" > ~/.msmtprc
          echo "account gmail" >> ~/.msmtprc
          echo "host smtp.gmail.com" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "user ${{ secrets.SMTP_USER }}" >> ~/.msmtprc
          echo "password ${{ secrets.SMTP_PASS }}" >> ~/.msmtprc
          echo "from ${{ secrets.SMTP_USER }}" >> ~/.msmtprc
          echo "account default : gmail" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Send email with attachment
        run: |
          echo "Please find the Postman test report attached." | mutt -s "Postman API Test Report" \
          -a ./postman/report.html -- ${{ secrets.TO_EMAIL }}
